<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <meta name="description" content="@yield('meta_desc','Страница авторизации')">

    <!-- fontawesome -->
    <link rel="stylesheet" href="{{asset('styles/all.css')}}">

    <link rel="stylesheet" href="{{asset('styles/auth/auth.css')}}" />
    <!-- Custom alert-message   -->
    <link rel="stylesheet" href="{{asset('styles/popup/popup.css')}}">

    <script src="{{asset('scripts/spinner/spinner.js')}}"></script>
    <!--    <link rel="stylesheet" href="fonts.css" />-->
    <title>@yield('title','Авторизация')</title>
</head>
<body class="no-scroll">

<!--Прелоадер-->
<div class="overlay">
    <!--    --><? //xml version="1.0" encoding="utf-8"?>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
         style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="200px"
         height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <circle cx="50" cy="50" r="32" stroke-width="8" stroke="#4481eb"
                stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round">
            <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" keyTimes="0;1"
                              values="0 50 50;360 50 50"></animateTransform>
        </circle>
        <!-- [ldio] generated by https://loading.io/ --></svg>
</div>

{{--<div class="container <?=($this->routeParams['action'] === 'profile')?'sign-up-mode':''?>">--}}
{{--    <?= $content ?>--}}
{{--</div>--}}

<div class="container @if(Illuminate\Support\Facades\Route::currentRouteName()==='cabinet') sign-up-mode @endif">
    @yield('content')
</div>

<!-- --------------------------- Custom alert-message ---------------------------------------- -->

<div class="bg-modal-popup">
    <div class="popup center">
        <div class="icon">
            <i class="fas fa-check-circle"></i>
        </div>
        <h1 class="title">
            Success!!
        </h1>
        <p class="description">
            Сообщение
        </p>
        <button id="dismiss-popup-btn"  class="btn solid">
            <i class="fas fa-spinner fa-spin del"></i><span class="text">Закрыть</span>
        </button>

    </div>
</div>

<!-- -------------x------------- Custom alert-message--------------------x------------------- -->

<!-- Jquery Library file -->
<script src="{{asset('scripts/Jquery3.4.1.min.js')}}"></script>
<!-- Custom Javascript alert-message -->
<script src="{{asset('scripts/popup/popup.js')}}"></script>

<script src="{{asset('scripts/form/form.js')}}"></script>
<script src="{{asset('scripts/auth/auth.js')}}"></script>
</body>
</html>
