<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <meta name="description" content="@yield('meta_desc','Мой блог')">

    <title>@yield('title','Мой блог')</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{asset('styles/all.css')}}">


    <!-- --------- Owl-Carousel ------------------->
    <link rel="stylesheet" href="{{asset('styles/vendors/owl-carousel/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('styles/vendors/owl-carousel/owl.theme.default.min.css')}}">

    <!-- ------------ AOS Library ------------------------- -->
    <link rel="stylesheet" href="{{asset('styles/vendors/aos/aos.css')}}">

    <!-- Custom Style   -->
    <link rel="stylesheet" href="{{asset('styles/frontend/style.css')}}">

    <!-- Custom alert-message   -->
    <link rel="stylesheet" href="{{asset('styles/popup/popup.css')}}">

    <script src="{{asset('scripts/spinner/spinner.js')}}"></script>

    @yield('styles','')
</head>
<body class="no-scroll">


<!--Прелоадер-->
<div class="overlay">
    <!--    --><? //xml version="1.0" encoding="utf-8"?>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
         style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="200px"
         height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <circle cx="50" cy="50" r="32" stroke-width="8" stroke="#4481eb"
                stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round">
            <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" keyTimes="0;1"
                              values="0 50 50;360 50 50"></animateTransform>
        </circle>
        <!-- [ldio] generated by https://loading.io/ --></svg>
</div>
<!-- ----------------------------  Navigation ---------------------------------------------- -->
<nav class="nav">

    <div class="nav-brand">
        <a href="{{route('main')}}" class="text-gray">Мой блог</a>
    </div>
    <div class="toggle-collapse">

        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </div>

    <ul class="nav-items">
        <li class="nav-link">
            <a href="{{route('main')}}">Главная</a>
        </li>
        <li class="nav-link">
            <a href="#">Категории</a>
        </li>
        <li class="nav-link">
            <a href="#">Теги</a>
        </li>
        @auth
            <li class="nav-link">
                <a href="{{route('logout')}}">Выйти</a>
            </li>
        @endauth
        @guest
            <li class="nav-link">
                <a href="{{route('enter')}}">Войти</a>
            </li>
        @endguest

        <li class="nav-link">
            <a href="#">Контакты</a>
        </li>
    </ul>

</nav>

<!-- ------------x---------------  Navigation --------------------------x------------------- -->

<!----------------------------- Main Site Section ------------------------------>

<main>
    @yield('content')
</main>

<!---------------x------------- Main Site Section ---------------x-------------->

<!-- --------------------------- Footer ---------------------------------------- -->

<footer class="footer">

    <div class="container">

        <div class="about-us" data-aos="fade-right" data-aos-delay="200">
            <h2>О сайте</h2>
            <p>Данный сайт разработан на PHP и JS. </p>
        </div>

        <div class="newsletter" data-aos="fade-right" data-aos-delay="200">
            <h2>Новости</h2>
            <p>Будь в курсе изменений</p>
            <div class="form-element">
                <input type="text" placeholder="Email"><span><i class="fas fa-chevron-right"></i></span>
            </div>
        </div>

        <div class="follow" data-aos="fade-left" data-aos-delay="200">
            <h2>Подпишись на нас</h2>

            <div class="social-media">
                <a href="#" class="social-icon">
                    <i class="fab fa-vk"></i>
                </a>
                <a href="#" class="social-icon">
                    <i class="fab fa-github-alt"></i>
                </a>
                <a href="#" class="social-icon">
                    <i class="fab fa-telegram-plane"></i>
                </a>
                <a href="#" class="social-icon">
                    <i class="fab fa-linkedin-in"></i>
                </a>
            </div>

        </div>
    </div>
    <div class="rights flex-row">
        <h4 class="text-gray">
            Мой блог ©{{ date("Y") }}Все права защищены
        </h4>
    </div>
    <div class="move-up">
        <span><i class="fas fa-arrow-circle-up fa-2x"></i></span>
    </div>
    <div id="particles-js"></div>
</footer>

<!-- -------------x------------- Footer --------------------x------------------- -->
<!-- --------------------------- Custom alert-message ---------------------------------------- -->

<div class="bg-modal-popup">
    <div class="popup center">
        <div class="icon">
            <i class="fas fa-check-circle"></i>
        </div>
        <h1 class="title">
            Success!!
        </h1>
        <p class="description">
            Сообщение
        </p>
        <button id="dismiss-popup-btn"  class="btn solid">
            <i class="fas fa-spinner fa-spin del"></i><span class="text">Закрыть</span>
        </button>

    </div>
</div>

<!-- -------------x------------- Custom alert-message--------------------x------------------- -->

<!-- Jquery Library file -->
<script src="{{asset('scripts/Jquery3.4.1.min.js')}}"></script>

<!-- --------- Owl-Carousel js ------------------->
<script src="{{asset('scripts/vendors/owl-carousel/owl.carousel.min.js')}}"></script>

<!-- ------------ AOS js Library  ------------------------- -->
<script src="{{asset('scripts/vendors/aos/aos.js')}}"></script>

<!-- ------------ Particles js Library  ------------------------- -->
<script src="{{asset('scripts/vendors/particles/particles.min.js')}}"></script>
<script src="{{asset('scripts/vendors/particles/particles.app.js')}}"></script>

<!-- Custom Javascript alert-message -->
<script src="{{asset('scripts/popup/popup.js')}}"></script>

<!-- Custom Javascript file -->
<script src="{{asset('scripts/frontend/main.js')}}"></script>

<!-- Comments -->
{{--<script src="/public/scripts/main/comments.js?<?php        echo(rand(10,1000));?>"></script>--}}

<!-- Reactions -->
{{--<script src="/public/scripts/main/reactions.js?<?php        echo(rand(10,1000));?>"></script>--}}

@yield('scripts','')
</body>
</html>
